install: npm install
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: docs-main
  target-branch: master
branches:
  only:
    - docs-main
